repos:
  - repo: pre-commit-repos/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: pre-commit-repos/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v1.5.1'  # Use the sha / tag you want to point at
  #   hooks:
  #     - id: mypy

exclude: (^xarm_description)|(^asset/2004)
